# Generated by Django 5.1.4 on 2024-12-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='nome',
            field=models.CharField(default='teste', max_length=200),
        ),
    ]
